name: deploy-hugo

on:
  push:
    branches: [ main ]        # build on every push to main
  pull_request:               # optional: preview on PRs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true    # pulls the theme

      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.115.4'
          extended: true

      - name: Build
        run: hugo --minify    # outputs to ./public

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages   # auto-creates branch
